# Generated by Django 3.2.17 on 2023-02-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230208_1918'),
    ]

    operations = [
        migrations.RunSQL("""
            Insert into store_collectio (title)
            values ('salman shahbaz')
        """, """ 
        Delete from store_collection Where title = 'salman shahbaz' 
        """)
    ]
# Generated by Django 3.2.17 on 2023-02-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230208_1918'),
    ]

    operations = [
        migrations.RunSQL("""
            Insert into store_collection (title)
            values ('salman shahbaz')
        """, """ 
        Delete from store_collection Where title = 'salman shahbaz' 
        """)
    ]
